name: CI

on: 
  push:
    branches: 
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install awscli
      run: sudo apt-get install awscli -y
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install Gatsby
      run: |
        echo 'installing gatsby'
        npm install yarn 
        npm install gatsby-cli
    - name: Building Static Site
      run: |
        echo 'building static bundle'
        yarn
        ./gatsby build
    - name: Deploying bundle to bucket
      run: |
        echo 'copying site to s3 bucket'
        aws s3 cp public s3://dev.coffay.haus/ --recursive --region us-east-1 --acl public-read
        
